# Generated by Django 4.2.16 on 2024-10-19 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Court 3,4", "Court 3,4"),
                            ("Court 5,6", "Court 5,6"),
                            ("Court 7,8", "Court 7,8"),
                            ("Court 9,10", "Court 9,10"),
                            ("Court 11,12", "Court 11,12"),
                            ("Court 13,14", "Court 13,14"),
                            ("Court 15,16", "Court 15,16"),
                            ("Court 17,18", "Court 17,18"),
                            ("Court 19,20", "Court 19,20"),
                            ("Court 21,22", "Court 21,22"),
                            ("Court 23,24", "Court 23,24"),
                            ("Court 25,26", "Court 25,26"),
                            ("Court 27,28", "Court 27,28"),
                            ("Court 29,30", "Court 29,30"),
                            ("Court 31,32", "Court 31,32"),
                            ("Court 33,34", "Court 33,34"),
                        ],
                        default="Court 3,4",
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=datetime.datetime.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("16.00 - 17.00", "16.00 - 17.00"),
                            ("17.00 - 18.00", "17.00 - 18.00"),
                            ("18.00 - 19.00", "18.00 - 19.00"),
                            ("19.00 - 20.00", "19.00 - 20.00"),
                            ("20.00 - 21.00", "20.00 - 21.00"),
                            ("21.00 - 22.00", "21.00 - 22.00"),
                        ],
                        default="16.00 - 17.00",
                        max_length=30,
                    ),
                ),
                (
                    "time_ordered",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
